# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"

      - name: check dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run executable
        run: go run main.go

      - name: Test mock
        run: go test -gcflags=all=-l -v ./mock

      - name: Test cgo
        run: go test -gcflags=all=-l -v ./cgo

      - name: Test bytes
        run: go test -v ./byte

      - name: Test json
        run: go test -v ./json

      - name: Test array
        run: go test -v ./leetcode
